const actions = {
    SET_COUNTRIES: "SET_COUNTRIES",
    SET_COUNTRY: "SET_COUNTRY",
    SET_COUNTRYINFO: "SET_COUNTRYINFO",
    SET_TABLEDATA: "SET_TABLEDATA",
    SET_MAPCOUNTRIES: "SET_MAPCOUNTRIES",
    SET_MAPCENTER:"SET_MAPCENTER",
    SET_MAPZOOM:"SET_MAPZOOM",
    SET_CASESTYPE:"SET_CASESTYPE"
}


export default actions;